apiVersion: v1
kind: ServiceAccount
metadata:
  name: miner
  namespace: wocloud

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: miner
subjects:
  - kind: ServiceAccount
    name: miner
    namespace: wocloud
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
