apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: miner
  namespace: wocloud
  labels:
    k8s-app: miner
#    kubernetes.io/cluster-service: "true"
#    addonmanager.kubernetes.io/mode: Reconcile
spec:
  selector:
    matchLabels:
      k8s-app: miner
  template:
    metadata:
      labels:
        k8s-app: miner
        name: miner
#      annotations:
#        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      serviceAccountName: miner
      containers:
      - name: miner
        image: miner:0.1
        resources:
          # keep request = limit to keep this container in guaranteed class
          limits:
            cpu: 1000m
            memory: 5000Mi
          requests:
            cpu: 1000m
            memory: 5000Mi
        ports:
        - containerPort: 9999
        livenessProbe:
          httpGet:
            path: /
            port: 9999
          initialDelaySeconds: 30
          timeoutSeconds: 30
      tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
      - key: "node-role.kubernetes.io/master"
        operator: "Equal"
        effect: "NoSchedule"
      nodeSelector:
        node-role.kubernetes.io/master: ""
