apiVersion: v1
kind: Service
metadata:
  name: miner
  namespace: wocloud
  labels:
    k8s-app: miner
#    kubernetes.io/cluster-service: "true"
#    addonmanager.kubernetes.io/mode: Reconcile
spec:
  type: NodePort 
  selector:
    k8s-app: miner
  ports:
  - port: 81
    targetPort: 9999
    nodePort: 8981
  type: NodePort
