apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
  labels:
    type: grafana
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/grafana
