apiVersion: v1
kind: PersistentVolume
metadata:
  name: alertmanager-storage
  labels:
    type: storage
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/prometheus/alertmanager
