apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-pv
  labels:
    type: storage
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/prometheus/server
