apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: haproxy
  namespace: kube-system
  labels:
    k8s-app: haproxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: haproxy
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      nodeSelector:
        haproxy: 'yes'
      containers:
      - name: haproxy
        image: haproxy:1.7
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 10080
        - containerPort: 18080
        volumeMounts:
          - name: haproxy-config
            mountPath: /usr/local/etc/haproxy/haproxy.cfg
            subPath: haproxy.cfg
      volumes:
        - name: haproxy-config
          configMap:
            name: haproxy-config