apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-config
  namespace: kube-system
data:
  haproxy.cfg: |+
    global
            log 127.0.0.1 local0 info
            maxconn 4096
            user root
            group root
            daemon
            nbproc 1
            pidfile /run/haproxy.pid

    defaults
            mode    http
            retries 3
            maxconn 20000
            timeout connect 10s
            timeout client 30s
            timeout server 30s
            timeout check 2s

    listen  admin_stats
            bind 0.0.0.0:10080
            mode http
            log 127.0.0.1 local0 err
            stats refresh 30s
            stats uri /status
            stats realm welcome login\ Haproxy
            stats auth admin:123456
            stats hide-version
            stats admin if TRUE

    frontend api
            bind *:18080
            mode http
            option httplog
            option forwardfor
            log global
            default_backend api_backend

    backend api_backend
            mode http
            option redispatch
            option abortonclose
            balance roundrobin
            cookie SERVERID
            option httpchk GET /version
            server kube-apiserver1 172.20.2.150:8080 cookie api1 weight 2 check inter 2000 rise 2 fall 3
            server kube-apiserver2 172.20.5.101:8081 cookie api2 weight 2 check inter 2000 rise 2 fall 3